id: opecha:P007076
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG02530
  title: ཡར་ཀླུངས་གསོ་རིག་
  volume:
    9c81896d93d34d2186b557769b321415:
      image_group_id: I00KG07595
      title: Volume 1 of yar klungs gso rig
      volume_number: 1
      total_pages: 400
  author: ''
ebook_metadata:
  title: ཡར་ཀླུངས་གསོ་རིག་
  author: ''
  sku: P007076
  cover: cover.jpg
  layers:
  - pagination
