id: P007076
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG02530
  title: ཡར་ཀླུངས་གསོ་རིག་
  author: ''
  volumes:
    9c81896d93d34d2186b557769b321415:
      image_group_id: I00KG07595
      title: Volume 1 of yar klungs gso rig
      volume_number: 1
      total_pages: 400
      base_file: v001.txt
