id: P007076
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG02530
  title: ཡར་ཀླུངས་གསོ་རིག་
  author: ''
  volumes:
    03f8e3e0b0a34366be39d375df8f572c:
      image_group_id: I00KG07595
      title: ''
      volume_number: 1
      total_pages: 400
ebook_metadata:
  title: ཡར་ཀླུངས་གསོ་རིག་
  author: ''
  sku: P007076
  cover: cover.jpg
  layers:
  - pagination
