id: I01BFF65B
legacy_id: P007076
ocr_import_info:
  bdrc_scan_id: W00KG02530
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T19:51:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T01:46:32.362684+00:00'
last_modified: 2022-08-27 09:47:13.385051
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG02530
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG02530
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡར་ཀླུངས་གསོ་རིག
statistics:
  ocr_word_mean_confidence_index: 0.9306232366868917
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG07595:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG07595
      total_pages: 400
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG07595.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9306232366868917
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
