id: I01BFF65B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T19:54:12+00:00'
last_modified: '2022-06-09T04:36:44.215391+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG02530
  title: ཡར་ཀླུངས་གསོ་རིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A89D:
      image_group_id: I00KG07595
      title: Volume 1 of yar klungs gso rig
      total_pages: 400
      order: 1
      base_file: A89D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
